import { createAction } from '@reduxjs/toolkit';
import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {
    FETCH_USERS: `${STATE_REDUCER_KEY}/FETCH_USERS`,
    FETCH_USERS_REQUEST: `${STATE_REDUCER_KEY}/FETCH_USERS_REQUEST`,
    FETCH_USERS_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_USERS_SUCCESS`,
    FETCH_USERS_FAILURE: `${STATE_REDUCER_KEY}/FETCH_USERS_FAILURE`,

    FETCH_USER: `${STATE_REDUCER_KEY}/FETCH_USER`,
    FETCH_USER_REQUEST: `${STATE_REDUCER_KEY}/FETCH_USER_REQUEST`,
    FETCH_USER_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_USER_SUCCESS`,
    FETCH_USER_FAILURE: `${STATE_REDUCER_KEY}/FETCH_USER_FAILURE`,

    CREATE_USER: `${STATE_REDUCER_KEY}/CREATE_USER`,
    CREATE_USER_REQUEST: `${STATE_REDUCER_KEY}/CREATE_USER_REQUEST`,
    CREATE_USER_SUCCESS: `${STATE_REDUCER_KEY}/CREATE_USER_SUCCESS`,
    CREATE_USER_FAILURE: `${STATE_REDUCER_KEY}/CREATE_USER_FAILURE`,

    UPDATE_USER: `${STATE_REDUCER_KEY}/UPDATE_USER`,
    UPDATE_USER_REQUEST: `${STATE_REDUCER_KEY}/UPDATE_USER_REQUEST`,
    UPDATE_USER_SUCCESS: `${STATE_REDUCER_KEY}/UPDATE_USER_SUCCESS`,
    UPDATE_USER_FAILURE: `${STATE_REDUCER_KEY}/UPDATE_USER_FAILURE`,

    DELETE_USER: `${STATE_REDUCER_KEY}/DELETE_USER`,
    DELETE_USER_REQUEST: `${STATE_REDUCER_KEY}/DELETE_USER_REQUEST`,
    DELETE_USER_SUCCESS: `${STATE_REDUCER_KEY}/DELETE_USER_SUCCESS`,
    DELETE_USER_FAILURE: `${STATE_REDUCER_KEY}/DELETE_USER_FAILURE`,
};


export const fetchUsers =  createAction(ACTION_TYPES.FETCH_USERS)
export const fetchUser =  createAction(ACTION_TYPES.FETCH_USER)
export const createUser =  createAction(ACTION_TYPES.CREATE_USER)
export const updateUser =  createAction(ACTION_TYPES.UPDATE_USER)
export const deleteUser =  createAction(ACTION_TYPES.DELETE_USER)